<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>14.0</LangVersion>
    <AssemblyName>MayaX-Battery</AssemblyName>
    <RootNamespace>MayaXBattery</RootNamespace>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/MayaX-Battery.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.IO" />
    <Resource Include="Assets/MayaX-Battery.ico" />
  </ItemGroup>

</Project>
